
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ADD DIV DUMP MUL PRINT READ SET SUB id numComando : '(' READ id ')'Comando : '(' PRINT Exp ')'Comando : '(' SET id Exp ')'Comando : DUMPExp : '(' ADD Exp Termo ')' Exp : '(' SUB Exp Termo ')' Exp : TermoTermo : '(' MUL Termo Termo ')' Termo : '(' DIV Termo Termo ')' Termo : FactorFactor : '(' Exp ')'Factor : num"
    
_lr_action_items = {'(':([0,5,8,10,11,12,13,15,17,18,19,22,23,24,25,26,27,33,34,35,36,],[2,8,8,-7,-10,-12,8,8,8,25,25,25,-11,25,8,25,25,-5,-6,-8,-9,]),'DUMP':([0,],[3,]),'$end':([1,3,14,20,28,],[0,-4,-1,-2,-3,]),'READ':([2,],[4,]),'PRINT':([2,],[5,]),'SET':([2,],[6,]),'id':([4,6,],[7,13,]),'num':([5,8,10,11,12,13,15,17,18,19,22,23,24,25,26,27,33,34,35,36,],[12,12,-7,-10,-12,12,12,12,12,12,12,-11,12,12,12,12,-5,-6,-8,-9,]),')':([7,9,10,11,12,16,21,23,29,30,31,32,33,34,35,36,],[14,20,-7,-10,-12,23,28,-11,33,34,35,36,-5,-6,-8,-9,]),'ADD':([8,],[15,]),'SUB':([8,],[17,]),'MUL':([8,25,],[18,18,]),'DIV':([8,25,],[19,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Comando':([0,],[1,]),'Exp':([5,8,13,15,17,25,],[9,16,21,22,24,16,]),'Termo':([5,8,13,15,17,18,19,22,24,25,26,27,],[10,10,10,10,10,26,27,29,30,10,31,32,]),'Factor':([5,8,13,15,17,18,19,22,24,25,26,27,],[11,11,11,11,11,11,11,11,11,11,11,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Comando","S'",1,None,None,None),
  ('Comando -> ( READ id )','Comando',4,'p_Comando_ler','to_sexp_yacc.py',9),
  ('Comando -> ( PRINT Exp )','Comando',4,'p_Comando_escrever','to_sexp_yacc.py',14),
  ('Comando -> ( SET id Exp )','Comando',5,'p_Comando_atrib','to_sexp_yacc.py',18),
  ('Comando -> DUMP','Comando',1,'p_Comando_despejar','to_sexp_yacc.py',22),
  ('Exp -> ( ADD Exp Termo )','Exp',5,'p_Exp_add','to_sexp_yacc.py',26),
  ('Exp -> ( SUB Exp Termo )','Exp',5,'p_Exp_sub','to_sexp_yacc.py',30),
  ('Exp -> Termo','Exp',1,'p_Exp_termo','to_sexp_yacc.py',34),
  ('Termo -> ( MUL Termo Termo )','Termo',5,'p_Termo_mul','to_sexp_yacc.py',38),
  ('Termo -> ( DIV Termo Termo )','Termo',5,'p_Termo_div','to_sexp_yacc.py',42),
  ('Termo -> Factor','Termo',1,'p_Termo_Factor','to_sexp_yacc.py',50),
  ('Factor -> ( Exp )','Factor',3,'p_Factor_group','to_sexp_yacc.py',54),
  ('Factor -> num','Factor',1,'p_Factor_num','to_sexp_yacc.py',58),
]
