
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'PA PF VIRG alfanum number\n    Lista : PA PF\n          | PA Elementos PF\n\n    Elementos : Elemento\n              | Elementos VIRG Elemento\n    \n    Elemento : alfanum \n             | number\n    '
    
_lr_action_items = {'PA':([0,],[2,]),'$end':([1,3,8,],[0,-1,-2,]),'PF':([2,4,5,6,7,10,],[3,8,-3,-5,-6,-4,]),'alfanum':([2,9,],[6,6,]),'number':([2,9,],[7,7,]),'VIRG':([4,5,6,7,10,],[9,-3,-5,-6,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Lista':([0,],[1,]),'Elementos':([2,],[4,]),'Elemento':([2,9,],[5,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Lista","S'",1,None,None,None),
  ('Lista -> PA PF','Lista',2,'p_grammar','listas_yacc.py',30),
  ('Lista -> PA Elementos PF','Lista',3,'p_grammar','listas_yacc.py',31),
  ('Elementos -> Elemento','Elementos',1,'p_grammar','listas_yacc.py',33),
  ('Elementos -> Elementos VIRG Elemento','Elementos',3,'p_grammar','listas_yacc.py',34),
  ('Elemento -> alfanum','Elemento',1,'p_grammar','listas_yacc.py',36),
  ('Elemento -> number','Elemento',1,'p_grammar','listas_yacc.py',37),
]
