
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPAREN NUM PAL RPARENlisp : sexpsexp : PALsexp : NUMsexp : LPAREN sexplist RPARENsexplist : sexp sexplistsexplist : '
    
_lr_action_items = {'PAL':([0,3,4,5,7,8,],[3,-2,-3,3,3,-4,]),'NUM':([0,3,4,5,7,8,],[4,-2,-3,4,4,-4,]),'LPAREN':([0,3,4,5,7,8,],[5,-2,-3,5,5,-4,]),'$end':([1,2,3,4,8,],[0,-1,-2,-3,-4,]),'RPAREN':([3,4,5,6,7,8,9,],[-2,-3,-6,8,-6,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lisp':([0,],[1,]),'sexp':([0,5,7,],[2,7,7,]),'sexplist':([5,7,],[6,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lisp","S'",1,None,None,None),
  ('lisp -> sexp','lisp',1,'p_lisp','sexp_yacc.py',9),
  ('sexp -> PAL','sexp',1,'p_sexp_pal','sexp_yacc.py',14),
  ('sexp -> NUM','sexp',1,'p_sexp_num','sexp_yacc.py',20),
  ('sexp -> LPAREN sexplist RPAREN','sexp',3,'p_sexp_sexplist','sexp_yacc.py',25),
  ('sexplist -> sexp sexplist','sexplist',2,'p_sexplist_sexp','sexp_yacc.py',30),
  ('sexplist -> <empty>','sexplist',0,'p_sexplist_empty','sexp_yacc.py',35),
]
